title: "Welcome to Wing's Blog" # This will be used as the <title> of the page
author: "Charin Wing"
description: "Recording my thoughts, lessons, things about RL, DL, Robotics" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "wcy0590@gmail.com"
twitter_username: "wing0night"
github_username: "wing0night"
linkedin_username: "Charin Wing"
#facebook_username: username
#flickr_username: username
instagram_username: "wing0night"
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
