# Site settings
title: Wing's Blog
email: wcy0590@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A clean, minimalist blog inspired by Medium.com design.
  Writing about technology, thoughts, and life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wing0night.github.io" # GitHub Pages will set this automatically

# Author settings
author: Wing
brief-intro: Developer & Writer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Social links
social:
  github: wing0night
  twitter: wing0night
  linkedin: charin-wing-27590431a

# Comments (using Disqus)
disqus_shortname: # your-disqus-shortname

# Google Analytics
google_analytics: # your-google-analytics-id

# Excerpt separator
excerpt_separator: "\n\n\n\n"

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: CV
    url: /cv/
  - title: Archive
    url: /archive/
  - title: Tags
    url: /tags/
